spring:
  application:
    name: currency-rate
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver

  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

  liquibase:
    changeLog: classpath:/db/changelog/db.changelog-main.yml

server:
  port: 8080
